include:
 - project: "osdu/platform/ci-cd-pipelines"
   file: "standard-setup.yml"

stages:
  - review
  - build
  - coverage
  - containerize
  - scan

include:
 - project: "osdu/platform/ci-cd-pipelines"
   file: "build/maven.yml"

 - project: "osdu/platform/ci-cd-pipelines"
   file: "cloud-providers/azure.yml"

.maven:
  image: maven:3.9.3-eclipse-temurin-17

