apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: schema-cleanup-secret
  namespace: "{{ .Values.namespace }}"
data:
  blob_account_key: {{ $.Values.secret.blob_account_key }}
  blob_account_name: {{ $.Values.secret.blob_account_name }}
  cosmos_host: {{ $.Values.secret.cosmos_host }}
  cosmos_key: {{ $.Values.secret.cosmos_key }}
  schema_query_params_id: {{ $.Values.secret.schema_query_params_id }}